export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434842",
        "surface-tint": "#506351",
        "secondary-fixed-dim": "#eeb9bd",
        "tertiary-fixed": "#f0e0cd",
        error: "#ba1a1a",
        "surface-dim": "#dcdad5",
        "inverse-primary": "#b7ccb6",
        "primary-fixed-dim": "#b7ccb6",
        "surface-bright": "#fcf9f4",
        "tertiary-fixed-dim": "#d3c4b2",
        "primary-fixed": "#d3e8d1",
        "on-surface": "#1c1c19",
        "surface-container-high": "#ebe8e3",
        primary: "#506351",
        secondary: "#7c5357",
        "on-error": "#ffffff",
        "surface-container": "#f0ede9",
        "on-error-container": "#93000a",
        "inverse-surface": "#31302d",
        surface: "#fcf9f4",
        background: "#fcf9f4",
        "on-secondary-fixed": "#301216",
        tertiary: "#685d4e",
        "surface-container-highest": "#e5e2dd",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#221a0f",
        "on-primary-container": "#283929",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2dd",
        "on-tertiary-container": "#3d3427",
        "on-secondary-container": "#795154",
        "on-primary-fixed-variant": "#394b3a",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdadc",
        "surface-container-low": "#f6f3ee",
        "inverse-on-surface": "#f3f0eb",
        "on-secondary-fixed-variant": "#623c40",
        outline: "#747872",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c8c0",
        "secondary-container": "#fdc7cb",
        "on-primary-fixed": "#0e1f11",
        "primary-container": "#8fa38e",
        "tertiary-container": "#a99c8b",
        "on-background": "#1c1c19",
        "on-tertiary-fixed-variant": "#4f4538",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-padding": "120px",
        "container-max": "1200px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        motto: ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-lg": [
          "56px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        motto: ["24px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        soft: "0 20px 50px -10px rgba(74, 68, 63, 0.08)",
      },
    },
  },
  plugins: [],
};
